### ISSUE TITLE
Missing parameter UID when triggering IDP initiated authentication

### ISSUE THREAD

**Issue by thkus** [flipboxfactory/saml-idp#27]
Hi, 

first of all thanks again for the plugin, which makes working with SAML pretty straight forward. As to the issue:

We are using: 

- Craft CMS 3.6.7
- flipboxfactory/saml-idp 1.3.2

We suddenly ran into issues, where calling the Login Url resulted in an Error from Craft regarding a missing parameter `uid`. 
We made an update to the site, but not to Craft or any SAML related feature. So i'm not sure what might cause the issue.

**Stacktrace**

```
2021-04-27 09:33:08 [-][1][qoo300ga4q7bpb4n1cs5o7abp0][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Required parameter missing: uid in /var/www/project/site/vendor/yiisoft/yii2/web/Controller.php:187
Stack trace:
#0 /var/www/project/site/vendor/yiisoft/yii2/base/InlineAction.php(51): yii\web\Controller->bindActionParams(Object(yii\base\InlineAction), Array)
#1 /var/www/project/site/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#2 /var/www/project/site/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('request', Array)
#3 /var/www/project/site/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('request', Array)
#4 /var/www/project/site/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('saml-idp/login/...', Array)
#5 /var/www/project/site/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('saml-idp/login/...', Array)
#6 /var/www/project/site/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#7 /var/www/project/site/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/project/site/web/index.php(21): yii\base\Application->run()
#9 {main}
``` 

**Login URL** 

`https://www.example.de/sso/login/request/a65f5629-5c5c-4195-8772-0f4ce22afde0?RelayState=https://example.com/Om2G3?rt=FtAf8etQTUawbWkZzDCMQA`

**Workaround**

As a workaround, we now attached the UID (a65f5629-5c5c-4195-8772-0f4ce22afde0) additionally as a query parameter (&uid=) to the URL which resolves the issue. 

Is this something that sounds familiar to you?

**Comment by dsmrt** [comment]
👋 @thkus 

There were some updates with URL pathing recently to enable more explicit matching of both the IdP and the SP (which is new). This made me change the naming a little bit but if both the saml-core and the saml-idp package were updated together, this shouldn't be a problem. This is a package management issue on our side (not yours). I'm wondering if the saml-core package updated on you without saml-idp package updating. 

Can you update `flipboxfactory/saml-core` and make sure it's on the latest which is `3.2.7`? And then update `flipboxfactory/saml-idp` to `1.3.4`? Check the composer file for version requirements but I think you can just do `composer update flipboxfactory/saml-core flipboxfactory/saml-idp`.

These updates will put fix the urls so they work as they did before, ie, `https://www.example.de/sso/login/request/a65f5629-5c5c-4195-8772-0f4ce22afde0`, and the `uid` GET parameter (`?uid=<uid>`) won't work anymore because that parameter name has changed (it's now externalId). 

Sorry for the inconvenience! Let me know how this goes!

**Comment by dsmrt** [comment]
Let me know if you still need help here. Closing this for now.
